name: On Merge to Main

on:
  push:
    branches: [main]

jobs:
  update-linear:
    uses: ./.github/workflows/linear-ready-for-qa.yml
    secrets:
      LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
